module.exports = {
  MONGO_CONNECTION_URL: process.env.MONGO_DB_URL,
  PORT: process.env.PORT,
  SALT_ROUNDS:7,
  SECRET_KEY : 'baucuatomca',
  TOKEN_EXPIRY_TIME : '12h',
  TIME_LEFT_DEFAULT: 60,
  PENDING_COUNTDOWN_TIME: 5000,
  COUNTDOWN_INTERVAL_SECOND: 1000
};